### PR TITLE
Login Modal added

### PR DESCRIPTION
**Pull request by prampey**
A basic Login Modal component has been added. Other miscellaneous code changes due to automatic code linting

### CODE REVIEW

**Comment by UtkarshMe** [comment]
Rebased.

**Comment by UtkarshMe** [comment]
The build is failing though?

**Comment by mukkachaitanya** [comment]
Let it be for now. The code requires some improvements and has some inherent bugs. I will try to rectify them and push commit(s) by Monday.

**Comment by mukkachaitanya** [comment]
Known problems: 
Double lines in the `LoginModal` , couldn't find what is causing it. ( [#4472](https://github.com/callemall/material-ui/issues/4472) )

screen shot 2017-07-01 at 4 14 28 pm

**Comment by prampey** [comment]
I'll try to fix tests in another branch

**Pull request merged**
