### PR TITLE
Fixed Layout tests and Material-UI theming

### PR DESCRIPTION
**Pull request by prampey**
All tests pass now. Also, muiTheme is sent is passed on to the child components through '<App>' context.

### CODE REVIEW

**Comment by SebastinSanty** [comment]
@prampey I see them failing

**Comment by prampey** [comment]
@SebastinSanty The lints are failing, not the tests.

**Comment by prampey** [comment]
I'll open an issue for @mukkachaitanya to solve the lint problems for the Student Search component.

**Comment by SebastinSanty** [comment]
@prampey My bad, I didn't check the travis logs.

**Comment by prampey** [comment]
@mukkachaitanya If you wish to pass ApolloClient through the context variable, you could refer to this commit.

**Comment by mukkachaitanya** [comment]
This seems fine, can be merged. I am work on the linting in #26 .

**Comment by prampey** [comment]
Okay, I will merge this then.

**Pull request merged**
