### PR TITLE
Fix linting errors

### PR DESCRIPTION
**Pull request by UtkarshMe**
Travis has been failing due to linting errors. These changed will:
- Change tabs to spaces
- Fix line length error
- Remove warning for anonymous functions

Although, the warnings are removed, it is highly recommended that someone name all 37 functions in the data models and turn on the warnings again.

### CODE REVIEW

**Comment by mukkachaitanya** [comment]
Ah, lovely @UtkarshMe! Add a reviewer so that your PR can be approved and merged

**Comment by mukkachaitanya** [comment]
Hey, can you actually commit this on #6? That ports the propose_models to models.

**Comment by UtkarshMe** [comment]
On it.

**Comment by UtkarshMe** [comment]
I added a pull request with this to ```models``` branch in your fork, so closed this.

**Comment by SebastinSanty** [comment]
Would be better if you can continue in this PR, as the intent of our PRs are different, right? Yes, as @mukkachaitanya told, the models have been ported, which might require you to rebase your branch. Shall I open this PR?

**Comment by UtkarshMe** [comment]
Works for me.

**Comment by SebastinSanty** [comment]
Rebasing will kill you, as there are so many things to rebase in here? Maybe just amend your commit and remove the files that conflict, and add them in a later commit.

**Comment by UtkarshMe** [comment]
yeah... :P

**Comment by UtkarshMe** [comment]
@SebastinSanty review please?

**Comment by SebastinSanty** [comment]
Merged ac415dc

**Comment by UtkarshMe** [comment]
Squash and merge?

**Pull request closed without merging**
